"""fix

Revision ID: ef9cd410606b
Revises: cec314d71cb8
Create Date: 2022-01-16 17:12:02.174645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9cd410606b'
down_revision = 'cec314d71cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terremoto', sa.Column('mag_type', sa.Text(), nullable=True))
    op.drop_column('terremoto', 'magType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terremoto', sa.Column('magType', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('terremoto', 'mag_type')
    # ### end Alembic commands ###
