"""init

Revision ID: cec314d71cb8
Revises: 
Create Date: 2022-01-16 12:35:07.308088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec314d71cb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terremoto',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mag', sa.Numeric(), nullable=True),
    sa.Column('place', sa.Text(), nullable=True),
    sa.Column('time', sa.BigInteger(), nullable=True),
    sa.Column('updated', sa.BigInteger(), nullable=True),
    sa.Column('tz', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('felt', sa.Integer(), nullable=True),
    sa.Column('cdi', sa.Numeric(), nullable=True),
    sa.Column('mmi', sa.Numeric(), nullable=True),
    sa.Column('alert', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('tsunami', sa.Integer(), nullable=True),
    sa.Column('sig', sa.Integer(), nullable=True),
    sa.Column('net', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('ids', sa.Text(), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('types', sa.Text(), nullable=True),
    sa.Column('nst', sa.Integer(), nullable=True),
    sa.Column('dmin', sa.Numeric(), nullable=True),
    sa.Column('rms', sa.Numeric(), nullable=True),
    sa.Column('gap', sa.Numeric(), nullable=True),
    sa.Column('magType', sa.Text(), nullable=True),
    sa.Column('tipe', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terremoto')
    # ### end Alembic commands ###
